### ISSUE TITLE
 Rpc Client getConsumer has error,msg is null

### ISSUE THREAD

**Issue by AllenRay** [smartloli/kafka-eagle#1]
按照文档安装成功，也启动起来了。但是在dashboard，无法正确显示broker数量，topic数量。查看后台发现error，表现为Rpc client getConsumer has error.

stack 如下
Rpc Client getConsumer has error,msg is null
java.lang.NullPointerException
	at org.smartloli.kafka.eagle.service.impl.DashboardServiceImpl.getKafkaConsumerNumbers(DashboardServiceImpl.java:78)
	at org.smartloli.kafka.eagle.service.impl.DashboardServiceImpl.panel(DashboardServiceImpl.java:123)
	at org.smartloli.kafka.eagle.service.impl.DashboardServiceImpl.getDashboard(DashboardServiceImpl.java:68)
	at org.smartloli.kafka.eagle.controller.DashboardController.dashboardAjax(DashboardController.java:77)
	at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by smartloli** [comment]
OK. First of all, you can confirm whether the Kafka consumer records are stored in topic, such as your version is 0.10.x, its default storage in topic. Second, whether your Kafka cluster is properly installed, and whether it is written to the message. Finally, thank you very much for your feedback.

**Comment by spiritonly** [comment]
Hi, i use Kafka-2.11-0.9.0.1, when i step in topic meta page, I got nothing but 'Processing...'，i looked chrome toolbar，get some errors：‘Failed to load resource: net::ERR_CONTENT_DECODING_FAILED’
![image](https://cloud.githubusercontent.com/assets/1271007/23784428/f981ee06-059c-11e7-8d3e-070dc1c8b3b4.png)

**Comment by smartloli** [comment]
@spiritonly The error code is 500, the server may have some exceptions, you can be convenient to provide a running log server, the log files in the logs directory under the ```ke_console.out```. ```Failed to load resource:; net:: ERR_CONTENT_DECODING_FAILED``` error message, it is because you have set up agent browser cache, you can try to clear the cache in the browser try it. Thank you very much for your feedback.
