### ISSUE TITLE
关于消费者offset的问题

### ISSUE THREAD

**Issue by bingzhan0613** [smartloli/kafka-eagle#107]
作者您好！
我有一个正在工作的集群kafka v_1.0.0 ，我的kafka集群之前是用zk来管理消费者偏移量的，后来将偏移量交给了kafka自己去做管理。所以，我有两份消费者offset【一份旧的在zk中，一份新的在kafka自己内部[__consumer_offsets]】.
现在用kafka-eagle来做管理，遇到了一个问题，
当我设置
`cluster1.kafka.eagle.offset.storage=zookeeper`
属性的时候，Consumer Topic的offset可以正常查看lag  【旧offset】;
但是当我将属性值设置为
`cluster1.kafka.eagle.offset.storage=kafka`的时候，确无法查看，
同时会有异常输出。。。
`INFO  [SimpleConsumer.ConsumerFetcherThread-kafka.eagle.system.group_prd-pt-kafkaeagle-180-1540825255725-971b4a1f-0-108] - Reconnect due to error:
java.net.SocketTimeoutException
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:211)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:81)
	at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129)
	at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:86)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:111)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:31)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:118)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:103)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)`

这是什么情况呢？？

**Comment by bingzhan0613** [comment]
@smartloli

**Comment by smartloli** [comment]
@bingzhan0613  Like this
```
kafka.eagle.zk.cluster.alias=cluster1,cluster2
cluster1.zk.list=dn1:2181,dn2:2181,dn3:2181
cluster2.zk.list=tdn1:2181,tdn2:2181,tdn3:2181

cluster1.kafka.eagle.offset.storage=kafka
cluster2.kafka.eagle.offset.storage=zookeeper
```
For details, please refer to the blog[Kafka Eagle Multi-Cluster](https://www.cnblogs.com/smartloli/p/9371904.html).

**Comment by bingzhan0613** [comment]
@smartloli  这是我的配置，
当我配置
`cluster1.kafka.eagle.offset.storage=kafka`
的时候，页面的offset是没有办法查看的，
如图：
![image](https://user-images.githubusercontent.com/12511065/47689927-00cbed80-dc27-11e8-9dff-d1fd45787708.png)

但是如果配置了zookeeper
查看消费情况是没有问题的：
![image](https://user-images.githubusercontent.com/12511065/47690597-9ff1e480-dc29-11e8-8814-cde51fb87497.png)

**Comment by bingzhan0613** [comment]
@smartloli  这是我的配置，
`
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=210.14.134.120:2181,210.14.134.99:2181,210.14.134.110:2181
kafka.zk.limit.size=25
kafka.eagle.webui.port=8001
cluster1.kafka.eagle.offset.storage=kafka
kafka.eagle.metrics.charts=false
kafka.eagle.sql.fix.error=false
`


当我配置
`cluster1.kafka.eagle.offset.storage=kafka`的时候，页面的offset是没有办法查看的，
如图：
![image](https://user-images.githubusercontent.com/12511065/47689927-00cbed80-dc27-11e8-9dff-d1fd45787708.png)

但是如果配置了zookeeper查看消费情况是没有问题的：
![image](https://user-images.githubusercontent.com/12511065/47690597-9ff1e480-dc29-11e8-8814-cde51fb87497.png)
