### ISSUE TITLE
use mysql db error

### ISSUE THREAD

**Issue by yangjiajun2014** [smartloli/kafka-eagle#108]
I try to start kafka-eagle on windows with mysql db,but get an error:

2018-11-02 17:26:48 ERROR [MySqlStoragePlugin.Thread-56] - Create mysql connection has error address[XXXX:3306\ke],username[XXXX],password[XXXX],msg is Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "3306\ke"'.
Exception in thread "Thread-56" java.lang.NullPointerException
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.tables(MySqlRecordSchema.java:65)
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.schema(MySqlRecordSchema.java:55)
        at org.smartloli.kafka.eagle.web.controller.StartupListener$ContextSchema.run(StartupListener.java:87)

How to solve it?

**Comment by bluegitter** [comment]
I modified the kafka.eagle.url, it works.
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc\:mysql\://127.0.0.1\:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=123456

**Comment by smartloli** [comment]
@yangjiajun2014 Windows OS ```File.separator``` is ```\```, Linux or Unix is ```/```. So if you debug code in windows, you can replace ```File.separator``` to ```/```.

**Comment by cocodroid** [comment]
Db url should not use File.separator, but use / directly,will the next version be fixed?
