### ISSUE TITLE
 ERROR [AlertQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2] - Quartz statistics offset has error,msg is n java.lang.NullPointerException

### ISSUE THREAD

**Issue by amosJinCloudwise** [smartloli/kafka-eagle#122]
kafka-eagle version 1.2.6
kafka version 2.11-0.10.2.0

2018-12-26 17:20:07 ERROR [AlertQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2] - Quartz statistics offset has error,msg is n
java.lang.NullPointerException
    at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.alert(AlertQuartz.java:173)
    at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.consumer(AlertQuartz.java:154)
    at org.smartloli.kafka.eagle.web.quartz.AlertQuartz.alertJobQuartz(AlertQuartz.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
    at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:2
    at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by smartloli** [comment]
Fixed by [v1.2.8](https://github.com/smartloli/kafka-eagle/tree/v1.2.8)
