### ISSUE TITLE
无法获取consumer信息

### ISSUE THREAD

**Issue by QstDz** [smartloli/kafka-eagle#135]
您好，我的kafka开了kerberos，确认配置没问题，用kafka-eagle可以创建删除topic，可以给topic发送消息等。但是无法获取到consumer信息，请问这个该怎么解决？

报错如下2019-01-21 16:27:09 ERROR [KafkaServiceImpl.http-nio-10002-exec-10] - Consumer Path[/consumers/console-consumer-75744/owners] is not exist.
2019-01-21 16:25:01 INFO  [KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Partition[42],OffsetPath[/consumers/kafka.eagle.system.group/offsets/__consumer_offsets/42] is not exist!
2019-01-21 16:15:00 ERROR [KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2] - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
org.apache.kafka.common.KafkaException: Failed create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:370)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:52)
	at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getKafkaConsumer(KafkaServiceImpl.java:660)
	at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.consumer(AlertQuartz.java:90)
	at org.smartloli.kafka.eagle.web.quartz.AlertQuartz.alertJobQuartz(AlertQuartz.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:153)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:140)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:65)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:88)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:346)
	... 13 more
Caused by: java.lang.IllegalArgumentException: No serviceName defined in either JAAS or Kafka config
	at org.apache.kafka.common.security.kerberos.KerberosLogin.getServiceName(KerberosLogin.java:303)
	at org.apache.kafka.common.security.kerberos.KerberosLogin.configure(KerberosLogin.java:92)
	at org.apache.kafka.common.security.authenticator.LoginManager.<init>(LoginManager.java:63)
	at org.apache.kafka.common.security.authenticator.LoginManager.acquireLoginManager(LoginManager.java:114)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:142)
	... 17 more

**Comment by smartloli** [comment]
@QstDz 
Hi,
Read Manual:
[Install Kafka Eagle](https://ke.smartloli.org/2.Install/2.Installing.html)
[Kafka Eagle Blog](https://www.cnblogs.com/smartloli/p/9371904.html)

**Comment by QstDz** [comment]
看了，没什么用啊，我的kafka是0.10.2+kafka2.2.0

**Comment by QstDz** [comment]
哦哦，好的，已经解决了，谢谢~！

**Comment by zengqinchris** [comment]
楼主怎么解决的，我也出现这个问题？分享一下
