### ISSUE TITLE
Consumers Offsets details没有数据

### ISSUE THREAD

**Issue by vcancy** [smartloli/kafka-eagle#17]
kafka版本 0.10.x
kafka-eagle版本：1.1.6
目前能看到Consumers，但是进入Consumers Offsets details页面一直显示Processing...

后台日志如下：
[2017-07-27 14:16:13] VerifiableProperties.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Verifying properties
 [2017-07-27 14:16:13] VerifiableProperties.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Property client.id is overridden to kafka.eagle.system.group
 [2017-07-27 14:16:13] VerifiableProperties.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Property metadata.broker.list is overridden to kafkanode0:9092,kafkanode1:9092,kafkanode2:9092
 [2017-07-27 14:16:13] VerifiableProperties.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Property request.timeout.ms is overridden to 30000
 [2017-07-27 14:16:13] ClientUtils$.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Fetching metadata from broker BrokerEndPoint(1,kafkanode1,9092) with correlation id 153 for 1 topic(s) Set(__consumer_offsets)
 [2017-07-27 14:16:13] SyncProducer.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Connected to kafkanode1:9092 for producing
 [2017-07-27 14:16:13] SyncProducer.kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-leader-finder-thread - INFO  - Disconnecting from kafkanode1:9092
 [2017-07-27 14:16:13] SimpleConsumer.ConsumerFetcherThread-kafka.eagle.system.group_iZ25x3jocmtZ-1501133782430-71836807-0-1 - INFO  - Reconnect due to error:
 java.nio.channels.ClosedChannelException
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:110)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:85)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
	at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:111)
	at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:31)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:118)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:103)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)

**Comment by smartloli** [comment]
@vcancy  Are your ```kafka broker``` and ```zookeeper``` normal?

**Comment by shensmart** [comment]
我一样的问题

**Comment by smartloli** [comment]
@shensmart Check your kafka broker.

**Comment by FrankDC** [comment]
请问这个问题是哪里的配置问题？
==> logs/error.log <==
[2018-09-28 11:05:07] OffsetsQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2 - ERROR - Quartz statistics offset haserror,msg is null
