### ISSUE TITLE
命令行生成和消费topic都正常，但是ksql 查询不出结果，也不报错

### ISSUE THREAD

**Issue by nihaojava** [smartloli/kafka-eagle#177]
kafka版本 ：2.10
![image](https://user-images.githubusercontent.com/22907016/58065728-3fbc9300-7bb9-11e9-8302-ab5591b1cbac.png)

**Comment by smartloli** [comment]
提交SQL时，你查看一下```$KE_HOME/logs/ke_console.out```日志，是否有异常信息。

**Comment by nihaojava** [comment]
没有异常信息
![image](https://user-images.githubusercontent.com/22907016/58140734-f597e800-7c72-11e9-9655-6a96d5c33ce6.png)
![image](https://user-images.githubusercontent.com/22907016/58140764-12342000-7c73-11e9-97fe-668452dc66a5.png)

**Comment by nihaojava** [comment]
问题太多了
[2019-05-23 18:20:55] DispatcherServlet.http-nio-8048-exec-19 - DEBUG - Could not complete request
 org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.json.JsonReadContext.createRootContext(II)Lcom/fasterxml/jackson/core/json/JsonReadContext;
	at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1303)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:977)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.smartloli.kafka.eagle.web.sso.filter.SSOFilter.doFilter(SSOFilter.java:82)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)

**Comment by smartloli** [comment]
Review issue #71
