### ISSUE TITLE
KafkaServer 不支持OffsetFetchRequest V2时会产生大量线程且不断增长最终导致内存爆满

### ISSUE THREAD

**Issue by cjk87927** [smartloli/kafka-eagle#189]
- Kafka-eagle版本:
 V1.3.3

- Kafka Version
V0.10.0.0

- Exception Stack
`ERROR [KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-3] - Get consumer offset has error, msg is org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:262)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getKafkaOffset(KafkaServiceImpl.java:826)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.getKafkaOffset(AlertQuartz.java:231)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.consumer(AlertQuartz.java:133)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz.alertJobQuartz(AlertQuartz.java:71)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.
`

- Code
https://github.com/smartloli/kafka-eagle/blob/b7f68e4a918d0179b81484b989a4403151bade5d/kafka-eagle-core/src/main/java/org/smartloli/kafka/eagle/core/factory/KafkaServiceImpl.java#L816

- Reason
AdminClient 获取offset报异常后没有关闭,加上quartz策略导致一直Thread一直增加直至内存爆掉,也可能导致kafka too many open file

- Advise
增加final close AdminClient

**Comment by smartloli** [comment]
Two ways:
1.you can checkout [v1.2.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.2.8.tar.gz);
2.if you can modify kafka broker ```server.properties``` file, like this :
```bash
inter.broker.protocol.version=NEW_KAFKA_VERSION (such as 1.0.0, 1.x, or newer)
log.message.format.version=NEW_KAFKA_VERSION (such as 1.0.0, 1.x, or newer)
```
