### ISSUE TITLE
unexpected error, closing socket connection and attempting reconnect java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by lynnyq** [smartloli/kafka-eagle#207]
2019-08-14 11:16:13 ERROR [ZooKeeperClient.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-10-EventThread] - [ZooKeeperClient] Auth failed.
2019-08-14 11:16:13 INFO  [ClientCnxn.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-10-SendThread(bj-yg-bi-prd-10-240-20-29-belle.lan:2181)] - Socket connection established to bj-yg-bi-prd-10-240-20-29-belle.lan/10.240.20.29:2181, initiating session
2019-08-14 11:16:13 WARN  [ClientCnxn.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-10-SendThread(bj-yg-bi-prd-10-240-20-29-belle.lan:2181)] - Session 0x0 for server bj-yg-bi-prd-10-240-20-29-belle.lan/10.240.20.29:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

**Comment by smartloli** [comment]
1. zookeeper startup acls ? 
2. ```telnet 10.240.20.29 2181``` is ok ?

**Comment by lynnyq** [comment]
1.未开启acls

2.# telnet 10.240.20.29 2181           
Trying 10.240.20.29...
Connected to 10.240.20.29.
Escape character is '^]'.

重启服务后，正常，然后隔一段时间web页面上就拿不到数据了。

![image](https://user-images.githubusercontent.com/19179078/63067806-4736d280-bf43-11e9-9229-7f2a813f54bd.png)

**Comment by smartloli** [comment]
Check your kafka server & zookeeper server status. Or provide more exception information.

**Comment by Mrzsy** [comment]
> 1.未开启acls
> 
> 2.＃telnet 10.240.20.29 2181
> 正在尝试10.240.20.29 ...
> 已连接到10.240.20.29。
> 转义字符为'^]'。
> 
> 重启服务后，正常，然后隔断web页面上就拿不到数据了。
> ![图片](https://user-images.githubusercontent.com/19179078/63067836-751c1700-bf43-11e9-8ad6-9f970eae6686.png)

问题解决了吗？我也遇到了同样的问题
