### ISSUE TITLE
很多错误日志

### ISSUE THREAD

**Issue by lynnyq** [smartloli/kafka-eagle#208]
2019-08-15 14:35:30 ERROR [TopicRankQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1] - Collector topic logsize has error, msg is null
java.lang.NullPointerException
        at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.getTopicRealLogSize(BrokerServiceImpl.java:418)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicLogsizeStats(TopicRankQuartz.java:126)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicRankQuartz(TopicRankQuartz.java:54)
        at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2019-08-15 14:35:31 ERROR [TopicRankQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1] - Collector topic capacity has error, msg is None.get
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:347)
        at scala.None$.get(Option.scala:345)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.findKafkaLeader(KafkaServiceImpl.java:1104)
        at org.smartloli.kafka.eagle.core.metrics.KafkaMetricsServiceImpl.topicCapacity(KafkaMetricsServiceImpl.java:298)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicCapacityStats(TopicRankQuartz.java:82)
        at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicRankQuartz(TopicRankQuartz.java:61)
        at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by smartloli** [comment]
What version of Kafka do you use?
