### ISSUE TITLE
NoSuchMethodError (jackson/core/json/JsonReadContext)

### ISSUE THREAD

**Issue by VictorZeng** [smartloli/kafka-eagle#210]
[2019-08-19 13:56:13] KafkaConsumer.http-nio-8048-exec-11 - DEBUG - [Consumer clientId=consumer-44, groupId=kafka.eagle.system.group] Kafka consumer has been closed
 [2019-08-19 13:56:13] DispatcherServlet.http-nio-8048-exec-11 - DEBUG - Could not complete request
 org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: com.fasterxml.jackson.core.json.JsonReadContext.createRootContext(II)Lcom/fasterxml/jackson/core/json/JsonReadContext;
        at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1303)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:977)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
        at org.smartloli.kafka.eagle.web.sso.filter.SSOFilter.doFilter(SSOFilter.java:82)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.json.JsonReadContext.createRootContext(II)Lcom/fasterxml/jackson/core/json/JsonReadContext;
        at com.fasterxml.jackson.databind.util.TokenBuffer$Parser.<init>(TokenBuffer.java:851)
        at com.fasterxml.jackson.databind.util.TokenBuffer.asParser(TokenBuffer.java:156)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:107)
        at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:82)
        at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:107)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:228)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:203)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:375)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:308)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2796)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1896)
        at org.apache.calcite.model.ModelHandler.<init>(ModelHandler.java:84)
        at org.apache.calcite.jdbc.Driver$1.onConnectionInit(Driver.java:97)
        at org.apache.calcite.avatica.UnregisteredDriver.connect(UnregisteredDriver.java:145)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at org.smartloli.kafka.eagle.core.sql.tool.JSqlUtils.query(JSqlUtils.java:85)
        at org.smartloli.kafka.eagle.core.sql.execute.KafkaSqlParser.execute(KafkaSqlParser.java:66)
        at org.smartloli.kafka.eagle.web.service.impl.TopicServiceImpl.execute(TopicServiceImpl.java:87)
        at org.smartloli.kafka.eagle.web.controller.TopicController.topicSqlLogicalAjax(TopicController.java:408)
        at org.smartloli.kafka.eagle.web.controller.TopicController$$FastClassBySpringCGLIB$$959771d4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
        at org.smartloli.kafka.eagle.web.controller.TopicController$$EnhancerBySpringCGLIB$$806f569a.topicSqlLogicalAjax(<generated>)
        at org.smartloli.kafka.eagle.web.controller.TopicController$$FastClassBySpringCGLIB$$959771d4.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
        at org.smartloli.kafka.eagle.web.controller.TopicController$$EnhancerBySpringCGLIB$$15497990.topicSqlLogicalAjax(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
        ... 46 more
[2019-08-19 13:56:13] DefaultListableBeanFactory.http-nio-8048-exec-11 - DEBUG - Returning cached instance of singleton bean 'sqlSessionFactory'
 [2019-08-19 13:56:13] DispatcherServlet.http-nio-8048-exec-11 - DEBUG - DispatcherServlet with name 'SpringMvc' processing GET request for [/ke/errors/500]
 [2019-08-19 13:56:13] RequestMappingHandlerMapping.http-nio-8048-exec-11 - DEBUG - Looking up handler method for path /errors/500
 [2019-08-19 13:56:13] RequestMappingHandlerMapping.http-nio-8048-exec-11 - DEBUG - Returning handler method [public org.springframework.web.servlet.ModelAndView org.smartloli.kafka.eagle.web.controller.ErrorPageController.e500(javax.servlet.http.HttpServletResponse) throws java.lang.Exception]
 [2019-08-19 13:56:13] DefaultListableBeanFactory.http-nio-8048-exec-11 - DEBUG - Returning cached instance of singleton bean 'errorPageController'
 [2019-08-19 13:56:13] DispatcherServlet.http-nio-8048-exec-11 - DEBUG - Last-Modified value for [/ke/errors/500] is: -1
 [2019-08-19 13:56:13] DefaultListableBeanFactory.http-nio-8048-exec-11 - DEBUG - Invoking afterPropertiesSet() on bean with name '/error/500'

**Comment by VictorZeng** [comment]
kafka version 1.0.1-cdh6.0.1

**Comment by VictorZeng** [comment]
The calcite-avatica.jar exist "jackson/core/json/JsonReadContext" , incompatible jackson version 2.9.6.
Please upgrade the Apache Calcite version > 1.6.0.

**Comment by VictorZeng** [comment]
@smartloli 这个问题我提交了一个PR，请合并一下吧。
