### ISSUE TITLE
kafka 2.3.0  get consumer error

### ISSUE THREAD

**Issue by superbool** [smartloli/kafka-eagle#235]
![image](https://user-images.githubusercontent.com/8575470/64778198-31421f00-d58e-11e9-9e27-4bd5dd487f27.png)

```
 [2019-09-12 18:39:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
 [2019-09-12 18:39:00] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception:
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 more
```

```
[2019-09-12 18:49:36] KafkaServiceImpl.http-nio-8048-exec-9 - INFO  - Get kafka consumer group has error, msg is Failed create new KafkaAdminClient
 [2019-09-12 18:49:36] KafkaServiceImpl.http-nio-8048-exec-10 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
```

**Comment by xjsaber** [comment]
same version，same problem
java_version:1.8.0 
zookeeper:3.4.13
kafka:2.3.0

**Comment by naughtyGitCat** [comment]
me too

**Comment by sunspeedzy** [comment]
Same problem
Kafka Eagle 1.3.9
Kafka version: CloudearKafka kafka-1.0.1-kafka3.1.1
java_version: 1.8.0_191

**Comment by zengqinchris** [comment]
有没有人解决这个问题？分享一下

**Comment by smartloli** [comment]
Try [v1.4.0](http://download.kafka-eagle.org/)

**Comment by columbus9963** [comment]
@smartloli dosen't fix the problem yet since upgrade kafka eagle to 1.4.0
```
2019-11-27 10:43:53] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
 [2019-11-27 10:43:53] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception: 
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
        at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        ... 3 more
[2019-11-27 10:43:53] ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job (DEFAULT.metricsDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: java.lang.NullPointerException
        at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        ... 3 more
```
![image](https://user-images.githubusercontent.com/57693768/69689205-43e6e180-1103-11ea-9599-ce0688b15189.png)
