### ISSUE TITLE
kafka SASL_PLAINTEXT 启用报错

### ISSUE THREAD

**Issue by milesforli** [smartloli/kafka-eagle#240]
ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-4 - ERROR - Job (DEFAULT.metricsDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 more

**Comment by smartloli** [comment]
Look at the cluster information of Kafka in the screenshot of the module ```ZK & Kafka``` of Kafka Eagle.

**Comment by milesforli** [comment]
是我配置文件的问题吗 

cluster1.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-eagle";

**Comment by smartloli** [comment]
Refer to Official Document Settings [Security Configure](https://docs.kafka-eagle.org/2.env-and-install/5.security).

**Comment by llnbe** [comment]
Specification set or not

**Comment by zengqinchris** [comment]
楼主有没有解决这个问题，我也遇到一样的问题，
[2019-11-16 17:48:00] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-2 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception: 
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 more
[2019-11-16 17:48:00] ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-2 - ERROR - Job (DEFAULT.metricsDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 more
