### ISSUE TITLE
AlertQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-3 - ERROR - Topic[test] Send alarm mail has error,msg is null

### ISSUE THREAD

**Issue by EvgenijO** [smartloli/kafka-eagle#244]
kafka-eagle-web-1.3.9
Kafka 2.3.0
java1.8.0.144
AlertQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-3 - ERROR - Topic[test] Send alarm mail has error,msg is null
2019-10-11 17:20:02 DEBUG [DataSourceUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Fetching JDBC Connection from DataSource
2019-10-11 17:20:02 DEBUG [SpringManagedTransaction.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@6b7028d6] will not be managed by Spring
2019-10-11 17:20:02 DEBUG [findAlertByCGT.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - ==>  Preparing: select * from ke_alarm WHERE `cluster`=? and `group`=? and `topic`=?
2019-10-11 17:20:02 DEBUG [findAlertByCGT.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - ==> Parameters: kafka(String), id_topic_test(String), topic_test(String)
2019-10-11 17:20:02 DEBUG [findAlertByCGT.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - <==      Total: 1
2019-10-11 17:20:02 DEBUG [SqlSessionUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@49c77698]
2019-10-11 17:20:02 DEBUG [DataSourceUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Returning JDBC Connection to DataSource
java.lang.NullPointerException
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:673)
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:633)
        at javax.mail.internet.InternetAddress.<init>(InternetAddress.java:111)
        at org.smartloli.kafka.eagle.api.email.MailServiceImpl.sendHtmlMail(MailServiceImpl.java:99)
        at org.smartloli.kafka.eagle.api.email.MailServiceImpl.send(MailServiceImpl.java:84)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.alert(AlertQuartz.java:180)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.consumer(AlertQuartz.java:148)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz.alertJobQuartz(AlertQuartz.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2019-10-11 17:20:02 ERROR [AlertQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Topic[topic_test] Send alarm mail has error,msg is null
2019-10-11 17:20:02 DEBUG [KafkaZKPoolUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1] - Get pool,and available size [99]
java.lang.NullPointerException
        at java.net.URI$Parser.parse(URI.java:3042)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:73)
        at org.smartloli.kafka.eagle.common.util.HttpClientUtils.doPostJson(HttpClientUtils.java:131)
        at org.smartloli.kafka.eagle.api.im.IMServiceImpl.sendJsonMsgByDingDing(IMServiceImpl.java:50)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.alert(AlertQuartz.java:199)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz$Consumer.consumer(AlertQuartz.java:148)
        at org.smartloli.kafka.eagle.web.quartz.AlertQuartz.alertJobQuartz(AlertQuartz.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2019-10-11 17:20:02 ERROR [HttpClientUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - Do post json request has error, msg is null

**Comment by smartloli** [comment]
Try [v1.4.0](http://download.kafka-eagle.org/)
