### ISSUE TITLE
我尝试封装了docker镜像，详见docker hub

### ISSUE THREAD

**Issue by wyfsxs** [smartloli/kafka-eagle#264]
https://hub.docker.com/repository/docker/wyfsxs/kafka-eagle/general

**Comment by smartloli** [comment]
Thank you very much. Let's have a look later.

**Comment by wuxingye** [comment]
地址后边加了kafka解析不了啊 10.10.10.227:2181/kafka

[2019-11-25 19:44:53] ClientCnxn.main-SendThread(ZkServer01:2181) - INFO  - Opening socket connection to server ZkServer01:2181. Will not attempt to authenticate using SASL (unknown error)
 [2019-11-25 19:44:53] ClientCnxn.main-SendThread(ZkServer01:2181) - WARN  - Session 0x0 for server ZkServer01:2181, unexpected error, closing socket connection and attempting reconnect
 java.nio.channels.UnresolvedAddressException
	at sun.nio.ch.Net.checkAddress(Net.java:101)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
