### ISSUE TITLE
MetricsQuartz#consumerTopicQuartz 出现 NullPointerException

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#265]
```
[2019-11-21 13:07:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-2 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
[2019-11-21 13:07:00] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-2 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception: 
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 more

```

**Comment by columbus9963** [comment]
suffered with the same issue!
@smartloli any ideas?

**Comment by chaozwn** [comment]
我也是这个问题解决了吗

**Comment by haiping216** [comment]
两样的问题

**Comment by libratears** [comment]
问题依旧……
