### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by superfenv** [smartloli/kafka-eagle#285]
[2019-12-13 18:24:33] DruidDataSource.Druid-ConnectionPool-Create-516053829 - ERROR - create connection error, url: "jdbc:mysql://xxx:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull", errorCode 0, state null
 java.sql.SQLException: connect error, url "jdbc:mysql://xxx:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull", driverClass com.mysql.jdbc.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1533)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2109)
[2019-12-13 18:25:03] DruidDataSource.Druid-ConnectionPool-Create-516053829 - ERROR - create connection error, url: "jdbc:mysql://xxx:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull", errorCode 0, state null
 java.sql.SQLException: connect error, url "jdbc:mysql://xxx:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull", driverClass com.mysql.jdbc.Driver
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1533)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2109)

**Comment by cocodroid** [comment]
Are you sure correct the database of settings ?
