### ISSUE TITLE
升级成1.4.2后Get kafka version from jmx has error, msg is kafka.common:type=AppInfo,name=Version

### ISSUE THREAD

**Issue by 839225516** [smartloli/kafka-eagle#291]
将kafka-eagle-web-1.3.9 升级成 kafka-eagle-web-1.4.2后有如下报错：

[2019-12-26 21:22:12] KafkaServiceImpl.http-nio-8048-exec-5 - ERROR - Get kafka version from jmx has error, msg is kafka.common:type=AppInfo,name=Version
 [2019-12-26 21:22:12] KafkaServiceImpl.http-nio-8048-exec-5 - ERROR - Get kafka version from jmx has error, msg is kafka.common:type=AppInfo,name=Version
 [2019-12-26 21:22:13] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1 - ERROR - Get kafka old version logsize & parse has error, msg is kafka.log:type=Log,name=LogEndOffset,topic=rdkafkatest_rnd75f66ab062254dad_0050_subscribe_adds_1,partition=0
 [2019-12-26 21:22:13] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1 - ERROR - Get kafka old version logsize & parse has error, msg is kafka.log:type=Log,name=LogEndOffset,topic=rdkafkatest_rnd4a0ba26a78921132_0042_many_topics,partition=0
 [2019-12-26 21:22:13] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-1 - ERROR - Get kafka old version logsize & parse has error, msg is kafka.log:type=Log,name=LogEndOffset,topic=rdkafkatest_rnd4d364093235820bd_0030_offset_commit,partition=1

这个要怎么排查，kafka没有做任何改变
kafka-eagle 界面只能查到 kafka的 Topic List Info； Consumers Info没有任何数据

**Comment by 839225516** [comment]
catalina.out 的报错信息：

2019-12-26 18:50:00 INFO  [DruidDataSource.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - {dataSource-1} inited
javax.management.InstanceNotFoundException: kafka.log:type=Log,name=LogEndOffset,topic=rdkafkatest_rnd3f790bfd6de7a0b8_0041_fetch_max_bytes,partition=0
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
        at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall.java:283)
        at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:260)
        at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:161)
        at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
        at javax.management.remote.rmi.RMIConnectionImpl_Stub.getAttribute(Unknown Source)
        at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.getAttribute(RMIConnector.java:903)


是连jmx连不上吗

**Comment by 839225516** [comment]
可以确定 jmx的端口是没有问题的

**Comment by 839225516** [comment]
已解决，我自己配置的问题

配置文件中，我改了 cluster1 cluster2
kafka.eagle.zk.cluster.alias=dev,test
dev.zk.list=
test.zk.list=
后面的配置cluster1 没跟着改
cluster1.kafka.eagle.sasl.enable=false

**Comment by KNWBIN** [comment]
我改了，还是有问题
