### ISSUE TITLE
服务正常，jmx端口也打开，Dashboard无数据，topic获取不到，cluster有数据但kafka版本不显示

### ISSUE THREAD

**Issue by renhuhao** [smartloli/kafka-eagle#317]
[2020-03-20 17:00:30]ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-3 - ERROR - Job (DEFAULT.topicRankDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'topicRankQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz] failed; nested exception is java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'topicRankQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicRankQuartz(TopicRankQuartz.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 more
[2020-03-20 17:02:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-6 - ERROR - Get kafka consumer has error,msg is org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups

**Comment by renhuhao** [comment]
kafka 2.3 kafka-eagle 1.4.4

**Comment by smartloli** [comment]
Please check your kafka cluster

[2020-03-20 17:02:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-6 - 
```
**ERROR - Get kafka consumer has error,msg is org.apache.kafka.common.KafkaException: Failed to find brokers to send ListGroups**
```

**Comment by geekyouth** [comment]
参考
https://github.com/smartloli/kafka-eagle/issues/321
