### ISSUE TITLE
kafka-eagle webUI界面无监控视图

### ISSUE THREAD

**Issue by 1063238280** [smartloli/kafka-eagle#330]
环境信息：
kafka为单机版kafka：2.11
JVM port ：9988
kafka-eagle版本为：1.4.4
问题：kafka-eagle界面可正常登陆，其他功能正常。但看不到kafka broker和zookeeper的监控界面
![image](https://user-images.githubusercontent.com/63490857/79037496-30e13380-7c04-11ea-9503-9a2db1f2e65d.png)
![image](https://user-images.githubusercontent.com/63490857/79037503-49514e00-7c04-11ea-8b49-cffea28f5ee9.png)
kafka-eagle配置中已经打开了监控试图参数：
![image](https://user-images.githubusercontent.com/63490857/79037483-173fec00-7c04-11ea-887d-789bf8410e42.png)

**Comment by smartloli** [comment]
Zookeeper Version ?

**Comment by 1063238280** [comment]
zookeeper version : 3.5.7

**Comment by 1063238280** [comment]
> Zookeeper Version ?

zookeeper version : 3.5.7

**Comment by smartloli** [comment]
`$KE_HOME/logs/ke_console.out` has error logs ?

**Comment by 1063238280** [comment]
> `$KE_HOME/logs/ke_console.out` has error logs ?
  2020-04-11 19:10:04 ERROR [TopicRankQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-2] - Write topic rank capacity end data has error,msg is 
### Error updating database.  Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
### The error may exist in org/smartloli/kafka/eagle/web/dao/TopicDao.xml
### The error may involve org.smartloli.kafka.eagle.web.dao.TopicDao.writeTopicRank-Inline
### The error occurred while setting parameters
### SQL: replace into   ke_topic_rank(`cluster`,`topic`,`tkey`,`tvalue`)   values         (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)
### Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
; uncategorized SQLException; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
org.springframework.jdbc.UncategorizedSQLException: 
### Error updating database.  Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
### The error may exist in org/smartloli/kafka/eagle/web/dao/TopicDao.xml
### The error may involve org.smartloli.kafka.eagle.web.dao.TopicDao.writeTopicRank-Inline
### The error occurred while setting parameters
### SQL: replace into   ke_topic_rank(`cluster`,`topic`,`tkey`,`tvalue`)   values         (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)    ,     (?,?,?,?)
### Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
; uncategorized SQLException; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:88)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:440)
	at com.sun.proxy.$Proxy15.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:271)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:62)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:93)
	at com.sun.proxy.$Proxy22.writeTopicRank(Unknown Source)
	at org.smartloli.kafka.eagle.web.service.impl.DashboardServiceImpl.writeTopicRank(DashboardServiceImpl.java:170)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicCapacityStats(TopicRankQuartz.java:193)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankQuartz.topicRankQuartz(TopicRankQuartz.java:80)
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:822)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:53)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2931)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:2929)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:131)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:493)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:426)
	... 16 more

**Comment by smartloli** [comment]
The product environment is recommended to use mysql for storage.

**Comment by leqii-com** [comment]
> The product environment is recommended to use mysql for storage.

你好，只想用 SQLite，如何解决这个报错呀
Cause: org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
; uncategorized SQLException; SQL state [null]; error code [5]; [SQLITE_BUSY]  The database file is locked (database is locked); nested exception is org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
