### ISSUE TITLE
Kerberos problem when using v1.1.9

### ISSUE THREAD

**Issue by captainzmc** [smartloli/kafka-eagle#36]
hello，when using v1.1.9 happened the following problems：

**My kafka version is 0.10.1 （HDP-2.6.1.0）**
**My config：**
`kafka.eagle.sasl.enable=true

kafka.eagle.sasl.protocol=SASL_PLAINTEXT

kafka.eagle.sasl.mechanism=PLAIN

kafka.eagle.sasl.client=/opt/kafka/kafka-eagle-web-1.1.9/conf/kafka_client_jaas.conf`

`[root@hd177 kafka-eagle-web-1.1.9]# cat conf/kafka_client_jaas.conf
KafkaClient {
 com.sun.security.auth.module.Krb5LoginModule required

 doNotPrompt=true

 useTicketCache=true

 principal="kafka/hd177.bd@BD"

 useKeyTab=true

 serviceName="kafka"

 keyTab="/etc/security/keytabs/kafka.service.keytab"

 client=true;

};`

**following issues：**
`[2017-11-02 16:30:00] SaslChannelBuilder.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-5 - INFO  - Failed to create channel due to 
 org.apache.kafka.common.KafkaException: Failed to configure SaslClientAuthenticator
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.configure(SaslClientAuthenticator.java:123)
	at org.apache.kafka.common.network.SaslChannelBuilder.buildChannel(SaslChannelBuilder.java:110)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:188)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:629)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:186)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:397)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:217)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:172)
	at kafka.admin.AdminClient.kafka$admin$AdminClient$$send(AdminClient.scala:49)
	at kafka.admin.AdminClient$$anonfun$sendAnyNode$1.apply(AdminClient.scala:60)
	at kafka.admin.AdminClient$$anonfun$sendAnyNode$1.apply(AdminClient.scala:58)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at kafka.admin.AdminClient.sendAnyNode(AdminClient.scala:58)
	at kafka.admin.AdminClient.findAllBrokers(AdminClient.scala:90)
	at kafka.admin.AdminClient.listAllGroups(AdminClient.scala:98)
	at kafka.admin.AdminClient.listAllConsumerGroups(AdminClient.scala:112)
	at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getKafkaConsumer(KafkaServiceImpl.java:785)
	at org.smartloli.kafka.eagle.web.quartz.OffsetsQuartz.execute(OffsetsQuartz.java:160)
	at org.smartloli.kafka.eagle.web.quartz.OffsetsQuartz.jobQuartz(OffsetsQuartz.java:146)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.apache.kafka.common.KafkaException: Failed to create SaslClient with mechanism PLAIN
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslClient(SaslClientAuthenticator.java:138)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.configure(SaslClientAuthenticator.java:121)
	... 27 more
Caused by: javax.security.sasl.SaslException: Cannot get userid/password [Caused by javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code doe
s not currently support obtaining a password from the user.]	at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:157)
	at com.sun.security.sasl.ClientFactoryImpl.createSaslClient(ClientFactoryImpl.java:94)
	at javax.security.sasl.Sasl.createSaslClient(Sasl.java:384)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$1.run(SaslClientAuthenticator.java:134)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator$1.run(SaslClientAuthenticator.java:129)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslClient(SaslClientAuthenticator.java:129)
	... 28 more
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Could not login: the client is being asked for a password, but the Kafka client code does not currently support obtaining a password from the user.
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:73)
	at com.sun.security.sasl.ClientFactoryImpl.getUserInfo(ClientFactoryImpl.java:136)
	... 35 more`

**Comment by captainzmc** [comment]
Is there any other place need to set up？

**Comment by captainzmc** [comment]
The problem solved  by setting：kafka.eagle.sasl.mechanism=GSSAPI
Now I can use kafka-eagle monitor Offsets Realtime details. 
When I click on Consumer Status(http://xx.xx.xx.xxx:xxx/ke/consumers/offset/myconsumer-group1/testtopic1/),the log has the following ERROR, but does not seem to affect use.Does it's because my consumer and producer API is used old version?

`[2017-11-03 10:56:57] KafkaServiceImpl.http-nio-9095-exec-1 - ERROR - Error communicating with Broker [hd177.bd:6667] to find Leader for [test222, 1] Reason: java.io.EOFException
 [2017-11-03 10:56:57] SimpleConsumer.http-nio-9095-exec-1 - INFO  - Reconnect due to error:
 java.io.EOFException
	at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:83)
	at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129)
	at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120)
	at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:86)
	at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
	at kafka.consumer.SimpleConsumer.send(SimpleConsumer.scala:111)
	at kafka.javaapi.consumer.SimpleConsumer.send(SimpleConsumer.scala:68)
	at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.findLeader(KafkaServiceImpl.java:133)
	at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getLogSize(KafkaServiceImpl.java:410)
	at org.smartloli.kafka.eagle.web.service.impl.OffsetServiceImpl.getLogSize(OffsetServiceImpl.java:136)
	at org.smartloli.kafka.eagle.web.service.impl.OffsetServiceImpl.getLogSize(OffsetServiceImpl.java:154)
	at org.smartloli.kafka.eagle.web.controller.OffsetController.offsetDetailAjax(OffsetController.java:106)
	at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:776)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:705)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:857)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.smartloli.kafka.eagle.web.sso.filter.SSOFilter.doFilter(SSOFilter.java:82)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:85)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
[2017-11-03 10:56:57] KafkaServiceImpl.http-nio-9095-exec-1 - ERROR - Error communicating with Broker [hd179.bd:6667] to find Leader for [test222, 1] Reason: java.io.EOFException
 [2017-11-03 10:56:57] KafkaServiceImpl.http-nio-9095-exec-1 - ERROR - [KafkaClusterUtils.getLogSize()] - Can't find metadata for Topic and Partition. Exiting
`

**Comment by smartloli** [comment]
@captainzmc Kafka Eagle v1.1.9 only supports SASL.
