### ISSUE TITLE
连接不上zookeeper

### ISSUE THREAD

**Issue by candiecandyy** [smartloli/kafka-eagle#376]
JDK: openJDK14
zookeeper: 3.6.1
kafka: 2.1.2-2.5.0
kafka-eagle: 2.0.0
Kafka和zookeeper均已正常启动，hosts已添加解析，`telnet kafka02 2181` 输出:
```
Trying 192.168.50.25...
Connected to kafka02.
Escape character is '^]'.
Connection closed by foreign host.
```
表示连接成功，但是kafka-eagle的日志中一直报错
```
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
2020-07-10 18:42:24 INFO  [ClientCnxn.main-SendThread(kafka02:2181)] - Opening socket connection to server kafka02/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-07-10 18:42:24 WARN  [ClientCnxn.main-SendThread(kafka02:2181)] - Session 0x0 for server kafka02/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
2020-07-10 18:42:24 INFO  [ClientCnxn.main-SendThread(kafka01:2181)] - Opening socket connection to server kafka01/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-07-10 18:42:24 WARN  [ClientCnxn.main-SendThread(kafka01:2181)] - Session 0x0 for server kafka01/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
2020-07-10 18:42:25 INFO  [ClientCnxn.main-SendThread(kafka03:2181)] - Opening socket connection to server kafka03/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
2020-07-10 18:42:25 WARN  [ClientCnxn.main-SendThread(kafka03:2181)] - Session 0x0 for server kafka03/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
2020-07-10 18:42:26 INFO  [ClientCnxn.main-SendThread(kafka02:2181)] - Opening socket connection to server kafka02/<unresolved>:2181. Will not attempt to authenti
```
server.properties配置
```
######################################
# multi zookeeper & kafka cluster list
######################################
kafka.eagle.zk.cluster.alias=cluster1,cluster2
cluster1.zk.list=kafka01:2181,kafka02:2181,kafka03:2181
#cluster2.zk.list=xdn10:2181,xdn11:2181,xdn12:2181

######################################
# zookeeper enable acl
######################################
cluster1.zk.acl.enable=false
cluster1.zk.acl.schema=digest
cluster1.zk.acl.username=test
cluster1.zk.acl.password=test123

######################################
# broker size online list
######################################
cluster1.kafka.eagle.broker.size=20

######################################
# zk client thread limit
######################################
kafka.zk.limit.size=25

######################################
# kafka eagle webui port
######################################
kafka.eagle.webui.port=8048

######################################
# kafka offset storage
######################################
cluster1.kafka.eagle.offset.storage=kafka
#cluster2.kafka.eagle.offset.storage=zk

######################################
# kafka metrics, 15 days by default
######################################
kafka.eagle.metrics.charts=true
kafka.eagle.metrics.retain=15


######################################
# kafka sql topic records max
######################################
kafka.eagle.sql.topic.records.max=5000
kafka.eagle.sql.fix.error=true

######################################
# delete kafka topic token
######################################
kafka.eagle.topic.token=keadmin

######################################
# kafka sasl authenticate
######################################
cluster1.kafka.eagle.sasl.enable=false
cluster1.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
cluster1.kafka.eagle.sasl.mechanism=SCRAM-SHA-256
cluster1.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="kafka-eagle";
cluster1.kafka.eagle.sasl.client.id=
cluster1.kafka.eagle.sasl.cgroup.enable=false
cluster1.kafka.eagle.sasl.cgroup.topics=

#cluster2.kafka.eagle.sasl.enable=false
#cluster2.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
#cluster2.kafka.eagle.sasl.mechanism=PLAIN
#cluster2.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka-eagle";
#cluster2.kafka.eagle.sasl.client.id=
#cluster2.kafka.eagle.sasl.cgroup.enable=false
#cluster2.kafka.eagle.sasl.cgroup.topics=

######################################
# kafka ssl authenticate
######################################
cluster3.kafka.eagle.ssl.enable=false
cluster3.kafka.eagle.ssl.protocol=SSL
cluster3.kafka.eagle.ssl.truststore.location=
cluster3.kafka.eagle.ssl.truststore.password=
cluster3.kafka.eagle.ssl.keystore.location=
cluster3.kafka.eagle.ssl.keystore.password=
cluster3.kafka.eagle.ssl.key.password=
cluster3.kafka.eagle.ssl.cgroup.enable=false
cluster3.kafka.eagle.ssl.cgroup.topics=

######################################
# kafka sqlite jdbc driver address
######################################
#kafka.eagle.driver=org.sqlite.JDBC
#kafka.eagle.url=jdbc:sqlite:/hadoop/kafka-eagle/db/ke.db
#kafka.eagle.username=root
#kafka.eagle.password=www.kafka-eagle.org

######################################
# kafka mysql jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://192.168.50.16:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=123456
```

**Comment by smartloli** [comment]
Make sure the Kafka-Eagle server successfully resolves your domain name

**Comment by candiecandyy** [comment]
> Make sure deploy the Kafka-Eagle `Linux OS` can successfully resolves your domain name

This is my hosts configuration:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
192.168.50.24   kafka01
192.168.50.25   kafka02
192.168.50.26   kafka03
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
The configuration of kakfa01, kafka02 and kafka03 is the same.
I can ping kafka01,kafka02 and kafka03 successfully.
My zookeeper and Kafka have been runned successfully.
I don't understand why kafka-eagle resolves failed，could you help me？Thanks.

**Comment by candiecandyy** [comment]
突然找到灵感，既然无法解析kafka01/<unresolved>，我就修改hosts如下:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
192.168.50.24   kafka01
192.168.50.25   kafka02
192.168.50.26   kafka03
192.168.50.24   kafka01/<unresolved>
192.168.50.25   kafka02/<unresolved>
192.168.50.26   kafka03/<unresolved>
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
添加了对kafka01-kafka03/<unresolved>的解析，然后发现启动成功了。可以肯定的是在我的环境下，eagle会在我的主机名后面添加特殊字符，我觉得这可能是一个BUG，望解决。

**Comment by sunthx** [comment]
+1

**Comment by lim1208** [comment]
@candiecandyy @smartloli 我也遇到这个问题了，配置hosts加<unresolved>解决了，可能是个bug吧。

**Comment by thirdcountry** [comment]
这个似乎没人维护了，知道现在也没有解决
