### ISSUE TITLE
kafka 2.5.0  java.lang.ClassCastException: java.io.IOException cannot be cast to javax.management.remote.JMXConnector

### ISSUE THREAD

**Issue by haochencheng** [smartloli/kafka-eagle#394]
[2020-08-07 04:41:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-9 - ERROR - Get kafka broker used cpu value has error, msg is 
 java.lang.ClassCastException: java.io.IOException cannot be cast to javax.management.remote.JMXConnector
        at org.smartloli.kafka.eagle.common.util.JMXFactoryUtils.connectWithTimeout(JMXFactoryUtils.java:73)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getUsedCpuValue(KafkaServiceImpl.java:1606)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.kafkaAssembly(MBeanQuartz.java:338)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.kafkaCluster(MBeanQuartz.java:245)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.mbeanQuartz(MBeanQuartz.java:88)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by smartloli** [comment]
Kafka JMX_PORT is open?

**Comment by haochencheng** [comment]
> Kafka JMX_PORT is open?

this error disappeared after i open kafka JMX_PORT .
