### ISSUE TITLE
zookeeper集群地址解析异常

### ISSUE THREAD

**Issue by qknavy** [smartloli/kafka-eagle#396]
2.0.1版本，以IP+端口号形式配置的zookeeper地址，未开启zk的acl，启动的时候解析地址异常（zookeeper是能够正常访问到的）：

[2020-08-13 15:04:17] ClientCnxn.main-SendThread(xx.xxx.xx.xxx:2181) - INFO  - Opening socket connection to server xx.xxx.xx.xxx/<unresolved>:2181. Will not attempt to authenticate using SASL (unknown error)
 [2020-08-13 15:04:17] ClientCnxn.main-SendThread(xx.xxx.xx.xxx:2181) - WARN  - Session 0x0 for server xx.xxx.xx.xxx/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
 java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)

为何会在最终连接zk的时候在ip后面拼一段东西？另外请问这种情况需要如何解决？

**Comment by smartloli** [comment]
Error address, such as `xx.xxx.xx.xxx/:2181` 
Normal address, such as `127.0.0.1:2181` or `127.0.0.1:2181/kafka01`
