### ISSUE TITLE
Matters " java.lang.ArrayIndexOutOfBoundsExcept"

### ISSUE THREAD

**Issue by KrisBobLea** [smartloli/kafka-eagle#43]
when I run KE, I got following error in ./logs/error.log.

 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'mbeanQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MBeanQuartz] failed; nested exception is java.lang.ArrayIndexOutOfBoundsExcept

what should I do?

**Comment by KrisBobLea** [comment]
Here has more details:


 [2017-12-07 16:15:00] ZkEventThread.ZkClient-EventThread-404-null - INFO  - Starting ZkClient event thread.
 [2017-12-07 16:15:00] ZKPoolUtils.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-2 - ERROR -
 [2017-12-07 16:15:00] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-2 - ERROR - Job DEFAULT.mbeanDetail threw an unhandled Exception:
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'mbeanQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MBeanQuartz] failed; nested exception is java.lang.ArrayIndexOutOfBoundsExcept
ion: Array index out of range: 0
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Vector.java:748)
        at org.smartloli.kafka.eagle.common.util.ZKPoolUtils.getZkClientSerializer(ZKPoolUtils.java:151)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getAllBrokersInfo(KafkaServiceImpl.java:235)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.execute(MBeanQuartz.java:70)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.mbeanQuartz(MBeanQuartz.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        ... 3 more
[2017-12-07 16:15:00] ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-2 - ERROR - Job (DEFAULT.mbeanDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'mbeanQuartz' on target class [class org.smartloli.kafka.eagle.w
eb.quartz.MBeanQuartz] failed; nested exception is java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'mbeanQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MBeanQuartz] failed; nested exception is java.lang.ArrayIndexOutOfBo
undsException: Array index out of range: 0
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Vector.java:748)
        at org.smartloli.kafka.eagle.common.util.ZKPoolUtils.getZkClientSerializer(ZKPoolUtils.java:151)
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getAllBrokersInfo(KafkaServiceImpl.java:235)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.execute(MBeanQuartz.java:70)
        at org.smartloli.kafka.eagle.web.quartz.MBeanQuartz.mbeanQuartz(MBeanQuartz.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)

**Comment by smartloli** [comment]
@KrisBobLea Please refer to the use manual for configuration. [https://ke.smartloli.org/](https://ke.smartloli.org/)
