### ISSUE TITLE
页面显示异常

### ISSUE THREAD

**Issue by lhzsdnu** [smartloli/kafka-eagle#436]
kafka 版本2.4.0  kafka-eagle 版本1.4.8

[2020-11-05 22:46:02] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
 [2020-11-05 22:46:02] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception: 
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException
	at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:283)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:267)
	... 3 more
[2020-11-05 22:46:02] ErrorLogger.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job (DEFAULT.metricsDetail threw an exception.
 org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:276)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more

**Comment by smartloli** [comment]
```
Get kafka consumer has error,msg is Failed create new KafkaAdminClient
```
Please check your kafka-eagle config file (`$KE_HOME/conf/system-config.properties`), And upgrade to the latest version([kafka-eagle-v2.0.2](http://www.kafka-eagle.org/index.html)).
