### ISSUE TITLE
dashborad界面找不到数据

### ISSUE THREAD

**Issue by jhxiaoming** [smartloli/kafka-eagle#452]
zookeeper和kafka本地都运行ok，eagler界面可以打开，但是界面没有数据，报错如下:
[2020-12-19 13:22:43] KafkaServiceImpl.http-nio-8048-exec-18 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient

 [2020-12-19 13:23:00] KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Get kafka consumer has error,msg is Failed create new KafkaAdminClient
 [2020-12-19 13:23:00] JobRunShell.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-1 - ERROR - Job DEFAULT.metricsDetail threw an unhandled Exception:
 org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'metricsConsumerTopicQuartz' on target class [class org.smartloli.kafka.eagle.web.quartz.MetricsQuartz] failed; nested exception is java.lang.NullPointerException
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
        at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)

Caused by: java.lang.NullPointerException
        at org.smartloli.kafka.eagle.core.factory.KafkaServiceImpl.getKafkaConsumer(KafkaServiceImpl.java:709)
        at org.smartloli.kafka.eagle.web.quartz.MetricsQuartz.metricsConsumerTopicQuartz(MetricsQuartz.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
        at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
        ... 3 more

centos 7下环境版本如下：

java 8u212
kafka  2.11-2.4.1
zookeeper 3.5.7
eagle 1.3.7

快救救孩子吧，都搞了1天半了。

**Comment by jhxiaoming** [comment]
找到问题了，zk都注册地址弄错了。sorry
