### ISSUE TITLE
Linux启动时出错 Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by CHENbt** [smartloli/kafka-eagle#471]
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
        at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:140)
        at sun.tools.jar.Main.extractFile(Main.java:1072)
        at sun.tools.jar.Main.extract(Main.java:981)
        at sun.tools.jar.Main.run(Main.java:311)
        at sun.tools.jar.Main.main(Main.java:1288)
错误: 找不到或无法加载主类 org.smartloli.kafka.eagle.plugin.progress.KafkaEagleProgress
错误: 找不到或无法加载主类 org.smartloli.kafka.eagle.plugin.progress.KafkaEagleProgress
错误: 找不到或无法加载主类 org.smartloli.kafka.eagle.plugin.progress.KafkaEagleProgress

**Comment by CloudFly1997** [comment]
我也是 请问解决了么？

**Comment by JasonLeeCoding** [comment]
感觉官方提供的 tar 包有问题 文件不完整 解压的时候就报错了
