### ISSUE TITLE
kafka-eagle配置zookeeper地址为：192.168.179.128:2181，连接zk时地址报错：Session 0x0 for server 192.168.179.128/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect

### ISSUE THREAD

**Issue by litaozijin** [smartloli/kafka-eagle#473]
* 环境：window10 +jdk14 .0.1+kafka-eagle-2.0.3
* 配置:  system-config.propertie配置文件
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=192.168.179.128:2181
![image](https://user-images.githubusercontent.com/23730841/107134481-71493500-692d-11eb-997a-3278a186d63d.png)
* 启动报错：
   2021-02-07 10:01:42 WARN  [ClientCnxn.RMI TCP Connection(192.168.179.128:2181)] - Session 0x0 for server 192.168.179.128/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)

**Comment by danny-ni513** [comment]
我也遇到了这个问题

**Comment by litaozijin** [comment]
> 我也遇到了这个问题
jdk14.0.1对于zk地址的处理和jdk1.8有点差异，使用jdk1.8是没有问题的

**Comment by litaozijin** [comment]
@danny-ni513   如果不想替换jdk环境，也可以采用下面这个方法：
  * 修改hosts文件（我的hosts文件路径是 ”C:\Windows\System32\drivers\etc\hosts“） ，增加 "192.168.179.128 zookeeper1/<unresolved>"
  * 启动服务时，Vmoptions增加启动参数 -Djdk.net.hosts.file=C:\Windows\System32\drivers\etc\hosts
  这样，在jdk14环境下也能正常使用
