### ISSUE TITLE
because "zkc" is null

### ISSUE THREAD

**Issue by HuUncle** [smartloli/kafka-eagle#483]
你好，我照着文档配置了Kafka以及zookeeper。
但是不能获取到Kafka的集群信息，如图
![微信截图_20210308154619](https://user-images.githubusercontent.com/19486270/110298244-5a325b80-802f-11eb-9079-ac5395a046a2.png)

jdk version
> 15.0.2

kafka version
> 2.13-2.7.0

zookeeper version
> 3.6.2

日志输出：
> 2021-03-08 16:55:00 ERROR [KafkaZKPoolUtils.Thread-11] - Error initializing zookeeper, msg is 
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at org.smartloli.kafka.eagle.common.util.KafkaZKPoolUtils.getZkClient(KafkaZKPoolUtils.java:119)
	at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.topicList(BrokerServiceImpl.java:367)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$CapacityStatsSubThread.topicCapacityStats(TopicRankSubTask.java:344)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$CapacityStatsSubThread.run(TopicRankSubTask.java:327)
2021-03-08 16:55:00 ERROR [KafkaZKPoolUtils.Thread-11] - Kafka cluster[cluster1.zk.list] address has null.
2021-03-08 16:55:00 ERROR [BrokerServiceImpl.Thread-11] - Get topic list has error, msg is 
java.lang.NullPointerException: Cannot invoke "kafka.zk.KafkaZkClient.pathExists(String)" because "zkc" is null
	at org.smartloli.kafka.eagle.core.factory.v2.BrokerServiceImpl.topicList(BrokerServiceImpl.java:369)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$CapacityStatsSubThread.topicCapacityStats(TopicRankSubTask.java:344)
	at org.smartloli.kafka.eagle.web.quartz.TopicRankSubTask$CapacityStatsSubThread.run(TopicRankSubTask.java:327)
2021-03-08 16:55:00 INFO  [DruidDataSource.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1] - {dataSource-1} inited

eagle配置文件

> kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=maxlead_datacenter_0.com:2181,maxlead_datacenter_1.com:2181,maxlead_datacenter_2.com:2181
kafka.eagle.webui.port=8048
kafka.eagle.metrics.charts=true
kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/opt/software/kafka-eagle/db/ke.db
kafka.eagle.username=root
kafka.eagle.password=123456

kafka启动脚本已添加
> if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
    #export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
fi

zookeeper配置文件
> 4lw.commands.whitelist=*

第一次使用Kafka，小白，见谅。

**Comment by smartloli** [comment]
Please used [Kafka Eagle V2.0.5](https://github.com/smartloli/kafka-eagle-bin/archive/v2.0.5.tar.gz)

**Comment by 1241407808** [comment]
请问是zk客户端设置该配置，还是服务端配置？
