### ISSUE TITLE
docker 部署 Get topic capacity has error

### ISSUE THREAD

**Issue by beckjin** [smartloli/kafka-eagle#530]
```
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | 2021-07-28 06:02:00 ERROR [TopicRankSubTask$CapacityStatsSubThread.Thread-34] - Get topic capacity has error, msg is 
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | 2021-07-28 06:02:00 ERROR [TopicRankSubTask$CapacityStatsSubThread.Thread-34] - Get topic capacity has error, msg is 
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | 2021-07-28 06:02:00 ERROR [TopicRankSubTask$CapacityStatsSubThread.Thread-34] - Get topic capacity has error, msg is 
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | 2021-07-28 06:02:00 ERROR [TopicRankSubTask$CapacityStatsSubThread.Thread-34] - Get topic capacity has error, msg is 
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | java.lang.NullPointerException
kafkaeagle_1  | 	at org.smartloli.kafka.eagle.web.service.impl.BScreenServiceImpl.getProducerAndConsumerRate(BScreenServiceImpl.java:69)
kafkaeagle_1  | 	at org.smartloli.kafka.eagle.web.controller.BScreenController.getProducerAndConsumerRealRateAjax(BScreenController.java:65)
kafkaeagle_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kafkaeagle_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kafkaeagle_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kafkaeagle_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
kafkaeagle_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
kafkaeagle_1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
kafkaeagle_1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
kafkaeagle_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
kafkaeagle_1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807)
kafkaeagle_1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
kafkaeagle_1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)
kafkaeagle_1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)
kafkaeagle_1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
kafkaeagle_1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
kafkaeagle_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
kafkaeagle_1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
kafkaeagle_1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
kafkaeagle_1  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
kafkaeagle_1  | 	at org.smartloli.kafka.eagle.web.sso.filter.SSOFilter.doFilter(SSOFilter.java:87)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:450)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
kafkaeagle_1  | 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
kafkaeagle_1  | 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
kafkaeagle_1  | 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
kafkaeagle_1  | 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
kafkaeagle_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
kafkaeagle_1  | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
kafkaeagle_1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
kafkaeagle_1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
kafkaeagle_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
kafkaeagle_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
kafkaeagle_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
kafkaeagle_1  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
kafkaeagle_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
kafkaeagle_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
kafkaeagle_1  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
kafkaeagle_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
kafkaeagle_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
kafkaeagle_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
kafkaeagle_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
kafkaeagle_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
kafkaeagle_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
kafkaeagle_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
kafkaeagle_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
kafkaeagle_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
kafkaeagle_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
kafkaeagle_1  | 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by beckjin** [comment]
V2.0.4
