### ISSUE TITLE
Create sqlite connection has error address[jdbc:sqlite:/hadoop/kafka-egale/db/ke.db], msg is path to '/hadoop/kafka-egale/db/ke.db': '/hadoop/kafka-egale' does not exist

### ISSUE THREAD

**Issue by kabitionno** [smartloli/kafka-eagle#74]
2018-05-14 13:54:45] SqliteStoragePlugin.Thread-56 - ERROR - Create sqlite connection has error address[jdbc:sqlite:/hadoop/kafka-egale/db/ke.db], msg is path to '/hadoop/kafka-egale/db/ke.db': '/hadoop/kafka-egale' does not exist
 [2018-05-14 13:54:46] SqliteStoragePlugin.Thread-63 - ERROR - Create sqlite connection has error address[jdbc:sqlite:/hadoop/kafka-egale/db/ke.db], msg is path to '/hadoop/kafka-egale/db/ke.db': '/hadoop/kafka-egale' does not exist
 [2018-05-14 13:55:00] DruidDataSource.http-nio-8585-exec-10 - ERROR - init datasource error, url: jdbc:sqlite:/hadoop/kafka-egale/db/ke.db
 java.sql.SQLException: path to '/hadoop/kafka-egale/db/ke.db': '/hadoop/kafka-egale' does not exist
        at org.sqlite.core.CoreConnection.open(CoreConnection.java:192)
        at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)

**Comment by smartloli** [comment]
@kabitionno msg is path to '/hadoop/kafka-egale/db/ke.db': ```'/hadoop/kafka-egale'``` does not exist. Please set ```kafka.eagle.url```
