### ISSUE TITLE
 Error reading field 'expire_timestamp'

### ISSUE THREAD

**Issue by AndrewChen2013** [smartloli/kafka-eagle#79]
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'expire_timestamp': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:72)
	at kafka.coordinator.GroupMetadataManager$.readOffsetMessageValue(GroupMetadataManager.scala:958)
	at kafka.coordinator.GroupMetadataManager.readOffsetMessageValue(GroupMetadataManager.scala)
	at org.smartloli.kafka.eagle.core.ipc.KafkaOffsetGetter.startOffsetSaslListener(KafkaOffsetGetter.java:185)
	at org.smartloli.kafka.eagle.core.ipc.KafkaOffsetGetter.run(KafkaOffsetGetter.java:308)

**Comment by smartloli** [comment]
@AndrewChen2013 What is the ```Kafka``` version that you use ?

**Comment by smartloli** [comment]
@AndrewChen2013 
This exception is caused by the inconsistency between the version of the Kafka server and the version used by you and the client application.
```
Note:
if server (version >= 0.10.x) ，but client (consumer & producer version < 0.10.x).
```
