### ISSUE TITLE
kafka-eagle-bin-1.2.0启动报错

### ISSUE THREAD

**Issue by 1528992118** [smartloli/kafka-eagle#98]
<pre>
# kafka jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://192.168.91.160:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=Enjoyor1234
</pre>
以上是我的数据库配置，相关ke数据库和表格我也已创建，请问启动的时候，为什么会有以下报错
<pre>
2018-08-16 18:28:40 INFO  [MySqlRecordSchema.Thread-56] - The [ke] database already exists. Do not need to create it.
2018-08-16 18:28:40 ERROR [MySqlStoragePlugin.Thread-56] - Create mysql connection has error address[192.168.91.160:3306\ke],username[root],password[Enjoyor1234],msg is Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "3306\ke"'.
Exception in thread "Thread-56" java.lang.NullPointerException
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.tables(MySqlRecordSchema.java:65)
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.schema(MySqlRecordSchema.java:55)
        at org.smartloli.kafka.eagle.web.controller.StartupListener$ContextSchema.run(StartupListener.java:80)
2018-08-16 18:28:40 INFO  [MySqlRecordSchema.Thread-63] - The [ke] database already exists. Do not need to create it.
2018-08-16 18:28:40 ERROR [MySqlStoragePlugin.Thread-63] - Create mysql connection has error address[192.168.91.160:3306\ke],username[root],password[Enjoyor1234],msg is Cannot load connection class because of underlying exception: 'java.lang.NumberFormatException: For input string: "3306\ke"'.
Exception in thread "Thread-63" java.lang.NullPointerException
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.tables(MySqlRecordSchema.java:65)
        at org.smartloli.kafka.eagle.plugin.mysql.MySqlRecordSchema.schema(MySqlRecordSchema.java:55)
        at org.smartloli.kafka.eagle.web.controller.StartupListener$ContextSchema.run(StartupListener.java:80)
</pre>

**Comment by smartloli** [comment]
@1528992118 ```"3306\ke"```? Maybe is ```"3306/ke"```

**Comment by 1528992118** [comment]
@smartloli Finally,I changed datasource with `SQLite`,but there is a new issue.When I used `/metrics/brokers` ,It has this exceptions
   <pre>
2018-08-17 10:59:31 ERROR [Mx4jServiceImpl.http-nio-8048-exec-5] - JMX service url[192.168.91.168:-1] create has error,msg is Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 192.168.91.168; nested exception is:
        java.net.ConnectException: Connection refused: connect]
java.lang.NullPointerException
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at java.lang.Double.valueOf(Double.java:502)
        at org.smartloli.kafka.eagle.common.util.StrUtils.numberic(StrUtils.java:70)
        at org.smartloli.kafka.eagle.common.util.StrUtils.assembly(StrUtils.java:80)
        at org.smartloli.kafka.eagle.web.service.impl.MetricsServiceImpl.getAllBrokersMBean(MetricsServiceImpl.java:164)
   </pre>
I used Kafka version is `2.11-2.0.0`,  why can not connection.

**Comment by smartloli** [comment]
@1528992118 You can refer to this blog. [https://www.cnblogs.com/smartloli/p/9371904.html](https://www.cnblogs.com/smartloli/p/9371904.html)

**Comment by 1528992118** [comment]
@smartloli ，非常感谢，已成功运行部署，还有一个小问题，为什么`ke.sh stop`这个命令会无效，我现在是部署在`windows-server`上的，用的`Git-2.14.1-64-bit.exe`工具，运行的`.sh`文件
